add styling to Hero component
Code-For-Chicago/code-for-chicago-gatsby pull request #16
Opened 2022-12-11 00:10 UTC by demirsergen

2022-12-11 17:13 UTC, ecuarezma commented on src/components/Hero.jsx
> +  font-family: 'Source Sans Pro';
We shouldn't need to specify the font anymore since it is added to the global styling.

2022-12-11 17:14 UTC, ecuarezma commented on src/components/Hero.jsx
> +  font-size: 16px;
The default font size is already at 16px, so this line can be omitted.

2022-12-11 17:31 UTC, ecuarezma requested changes
Hi Sergen! There are a few things I would address right away.  All pixel units should be converted to rem units, with @media queries (screen sizes, etc) being the exception (I believe border radius falls under this exception, too, but I can't remember, lol). This can be done by dividing the pixel units by 16 (1 rem = 16 px).  The other one is more of a semantic convention.  I would confirm with Doug, but I believe with styled components, the components themselves should start with, or at least include, "style" in the name. For example, ContentContainer would be better understood as StyledContentContainer.  Lastly, having both a HeroSection and ContentContainer feels a bit redundant, so I would consolidate the ContentContainer into the HeroSection so you have fewer levels and simplify the component a bit more. Feel free to message me with any questions!

2022-12-11 18:01 UTC, demirsergen commented
Hi Edgar,

While at may seem redundant to have HeroSection and ContentContainer, I think, a separate container for the content is necessary as the viewport changes. Because HeroSection changes to be flex and flex-row after 769px, ContentContainer, however, stays to be flex flex-column.

2022-12-11 18:34 UTC, ecuarezma commented
> Hi Edgar,
> 
> While at may seem redundant to have HeroSection and ContentContainer, I think, a separate container for the content is necessary as the viewport changes. Because HeroSection changes to be flex and flex-row after 769px, ContentContainer, however, stays to be flex flex-column.

Ok.  Sorry, it's hard to see what's happening without a visual (I haven't figured out how to preview it, yet) so I'm totally going purely on structural code reading, haha.

2022-12-11 18:40 UTC, demirsergen commented
It's all good! To be fair, without preview, it is difficult to see how the styling works. But good points on px vs. rem, I was purely following the Figma design file. Normally, in my personal projects, I only use rem and em.

2022-12-13 04:04 UTC, daleinen7 commented
Working on getting a preview now. Hopefully next few days it will be available. That will make reviewing much easier.

2022-12-16 00:06 UTC, closed without merging