create and style the LongTextInput component
Code-For-Chicago/code-for-chicago-gatsby pull request #27
Opened 2023-01-24 16:01 UTC by demirsergen

2023-01-26 04:54 UTC, daleinen7 requested changes
Can you add this component to the "components" page so that we can test it out?

2023-01-28 23:01 UTC, daleinen7 requested changes
Looks good so far. I have a few minor style requests, and then I want to confirm with Joseph something before we merge this. 

Let's match the active and focus states of the text inputs. Rather than having the outline be around the text, let's have it around the whole component. 
<img width="625" alt="Screen Shot 2023-01-28 at 4 51 21 PM" src="https://user-images.githubusercontent.com/6326891/215294692-6033240d-d95e-4be3-9925-c0fffd263a12.png">
<img width="504" alt="Screen Shot 2023-01-28 at 4 52 07 PM" src="https://user-images.githubusercontent.com/6326891/215294715-b86c26a0-a247-45a4-9e1d-597b184b3a10.png">

2023-01-28 23:01 UTC, daleinen7 commented on src/components/LongTextInput.jsx
> +  .max-word {
Looks like there shoudl also be an outline around the whole component when there is an error. 
<img width="382" alt="Screen Shot 2023-01-28 at 5 00 02 PM" src="https://user-images.githubusercontent.com/6326891/215295025-7f794a80-6f15-46f0-88f2-540263a5f32d.png">

2023-01-28 23:01 UTC, daleinen7 commented on src/components/LongTextInput.jsx
> +  const [maxWordCount, setMaxWordCount] = useState(300)
Let's get this value from props but set a default to "300".

2023-01-28 23:51 UTC, demirsergen commented
Made the requested styling changes. Once we have an answer whether it's word or character count, I can fix that as well.

2023-01-29 23:02 UTC, daleinen7 commented
> https://deploy-preview-27--codeforchicago.netlify.app

Yeah looks good otherwise. I'll let you know what I hear from Joseph.

2023-02-02 13:20 UTC, daleinen7 approved these changes

2023-02-07 00:26 UTC, merged