Nav mobile
Code-For-Chicago/code-for-chicago-gatsby pull request #33
Opened 2023-03-01 01:07 UTC by demirsergen

implement mobile navigation

2023-03-05 23:54 UTC, daleinen7 requested changes
Very close. It looks like the area where the user selects the nav is still a little off. 

<img width="318" alt="Screen Shot 2023-03-05 at 5 52 51 PM" src="https://user-images.githubusercontent.com/6326891/222993256-e342272e-6810-4450-8353-2dd3053d1a91.png">

Let's get the text centered between the faint gray lines. 

And then let's get the selection area to be within the gray lines.

2023-03-10 00:54 UTC, daleinen7 requested changes
Very very close. Let's just remove the margin at the top so it matches the figma. Otherwise I think this is ready to go. Great work. 
<img width="768" alt="Screen Shot 2023-03-09 at 6 53 47 PM" src="https://user-images.githubusercontent.com/6326891/224195429-1564119a-d64f-437f-8f05-748d712e702b.png">

2023-03-10 22:44 UTC, demirsergen commented
I'm not sure why but one of the global classnames we created (label-1) was adding 20px vertical margin.

2023-03-11 03:43 UTC, daleinen7 approved these changes

2023-03-11 03:43 UTC, merged