Component/radio option
Code-For-Chicago/code-for-chicago-gatsby pull request #38
Opened 2023-03-13 23:28 UTC by sammy-k

https://trello.com/c/gzsELF2k/471-radio-option

NOTE FOR DOUG: I am unsure of the best way or your preferred way to create dynamic classes based on props for different button states (error, disabled, standard, etc). I was initially going to have a bunch of conditional renders but thats going to be too WET.  I put a todo at the top of the RadioOption file so maybe we can discuss

2023-03-14 03:30 UTC, daleinen7 reviewed
Looking mostly good. I know there there's the few things we talked about. I have a few other notes too. Can we make the whole div activate the radio option? It looks like the hover states and active states all work. We just need to have them actually select the option.

2023-03-14 03:30 UTC, daleinen7 commented on src/components/Button.jsx
Haha, and I actually have a use for commenting on the file itself ... perfect timing. 

Anyway, can you let me know what you changed on this component? It's been heavily updated since this so you'll want to merge with main before merging this in.

2023-03-14 03:30 UTC, daleinen7 commented on src/components/RadioOption.jsx
> +// TODO: talk to Doug about best way to handle dynamic classes based on props
Just as a reminder: Copy the approach Edgar took on the button component.

2023-03-14 03:30 UTC, daleinen7 commented on src/components/RadioOption.jsx
> +  .button-container {
All this should be taken care of in the global reset. See if this works without the rule set. It should.

2023-03-26 21:08 UTC, daleinen7 requested changes
Doesn't look like I can select the radio button. You may need a "checked" property. 
https://www.pluralsight.com/guides/how-to-use-radio-buttons-in-reactjs

2023-05-08 00:07 UTC, sammy-k commented
I was still unable to implement selecting the radio button by clicking on the parent div.  Everything should be good beyond that though.  If its necessary that we click on the outside div to activate the radio state let me know and I may need to rebuild the component or heavily refactor

2023-06-10 14:26 UTC, daleinen7 approved these changes

2023-06-10 14:26 UTC, merged