generate dynamic pages for projects
Code-For-Chicago/code-for-chicago-gatsby pull request #54
Opened 2023-05-09 00:10 UTC by demirsergen

2023-05-23 14:34 UTC, daleinen7 requested changes

2023-05-23 14:34 UTC, daleinen7 commented on src/pages/projects/{MarkdownRemark.parent__(File)__name}.js
> +    <div>
Let's wrap this in a Layout component so that the header and footer show up.

2023-05-23 14:34 UTC, daleinen7 commented on src/pages/projects/{MarkdownRemark.parent__(File)__name}.js
> +      frontmatter {
Looks like images still aren't showing up on my end. Let me know if you need help pulling them from the CMS.

2023-05-24 01:36 UTC, daleinen7 commented on src/pages/projects/{MarkdownRemark.parent__(File)__name}.js
> +      frontmatter {
I imagine we'll need to merge @jscarpelli3 's PR for this to work. Once he finishes up with his ticket you can merge with `main` and we'll see if the images show up.

2023-06-06 22:27 UTC, daleinen7 commented
@demirsergen I finally got @jscarpelli3 's PR merged in. See if that fixes the image problems.

2023-06-10 13:29 UTC, daleinen7 commented
@demirsergen I actually dived a little deeper and there were further changes needed. We can talk about it Monday if you'll be around otherwise take a look at my changes and let me know if you have questions.

2023-06-10 13:30 UTC, daleinen7 approved these changes

2023-06-10 13:30 UTC, merged

2023-06-10 14:02 UTC, demirsergen commented
> 4935a86

I will definitely be there to understand it better, until then, I'll read the code to get an idea of how it works!