create and write markup for Hero component
Code-For-Chicago/code-for-chicago-gatsby pull request #7
Opened 2022-11-15 18:43 UTC by demirsergen

2022-11-16 04:13 UTC, daleinen7 requested changes
Good start. I'd like to set this up to be a little more reusable. Let's display most of the dynamic content through props. 

And then I have a note about the pre heading. I wish I could find the article I read about this but I couldn't find it again. Let me know if you have questions on how or why we're changing it. 

And then I think this will be ready to go.

2022-11-16 04:13 UTC, daleinen7 commented on src/components/Hero.jsx
> +      <div className="hero-content-container">
No need for this div. The above `section` tag will allow us to style this container as needed.

2022-11-16 04:13 UTC, daleinen7 commented on src/components/Hero.jsx
> +        <h4>A CODE FOR AMERICA BRIGADE</h4>
There's a lot of discussion on how to handle eyebrow text. There's no official way to handle it (some argue HTML does not modern designs). But we definitely can't have our `h` tags out of order. So here's how I think we should handle it;

Let's wrap lines 8 and 9 in an `h2` tag (most Hero's contain the page heading and that's what we'll assume is happening here). Then let's wrap "A CODE FOR AMERICA BRIGADE" in a `span` tag with a className of "eyebrow-text". 

And then one last semantic change on this line. Let's keep reusable and simply pass this content as a prop. 

So something like `eyebrowText`.

2022-11-16 04:13 UTC, daleinen7 commented on src/components/Hero.jsx
> +        <h1>Making community services work in a digital age</h1>
Let's change this to be dynamic content passed down from props. Something like `mainHeading`.

2022-11-16 04:13 UTC, daleinen7 commented on src/components/Hero.jsx
> +          We forge partnerships between neighbors who use technology to improve
Let's pass this paragraph content down via props so it's more reusable.

2022-11-16 05:06 UTC, demirsergen commented
There wasn't a comment for the <img /> element but I thought if we are making this component more reusable, maybe we should get the image url via props as well. I might be getting ahead of myself here, so please feel free to correct me if I'm missing something.

2022-11-25 18:24 UTC, daleinen7 approved these changes
Looks good!

2022-11-25 18:25 UTC, daleinen7 commented
> There wasn't a comment for the `<img />` element but I thought if we are making this component more reusable, maybe we should get the image url via props as well. I might be getting ahead of myself here, so please feel free to correct me if I'm missing something.

From the figma it looks like it will always be the skyline icon, but I'd rather error on the side of making the component reusable so good call on that.

2022-11-25 18:31 UTC, merged