Component check
Code-For-Chicago/code-for-chicago-gatsby pull request #75
Opened 2023-09-11 19:09 UTC by sammy-k

https://trello.com/c/EYFFQZiB

2023-09-15 12:30 UTC, daleinen7 requested changes
Looks good. 

Just a few minor change requests and it's good to go. Thanks!

2023-09-15 12:30 UTC, daleinen7 commented on .DS_Store
I have no idea why these .DS_Store pages are showing up. See if you can try to remove them. I am running into the same thing with other projects. Must have bene an OSX update.

2023-09-15 12:30 UTC, daleinen7 commented on src/pages/components.jsx
> +        <Footer />
Since the footer is on the page already, let's not include this.

2023-09-15 12:30 UTC, daleinen7 commented on src/pages/components.jsx
> +        <Nav />
Since the navs are technically on the page anyway, let's not include them.

2023-09-18 22:10 UTC, sammy-k commented on .DS_Store
strange - they arent showing up on my local branch.  Probably something we should look into

2023-09-18 23:58 UTC, daleinen7 approved these changes
@sammy-k Looks good except it's saying the conflict is with the `.DS_Store`.

2023-10-04 23:31 UTC, daleinen7 commented
> @sammy-k Looks good except it's saying the conflict is with the `.DS_Store`.

@sammy-k I _think_ all you need to do is add the .DS_Store file to the gitignore and it should resolve the conflict. I hope anyway.

2023-11-21 03:31 UTC, closed without merging