Create Checklist component and write markup & add icons to images/join-us
Code-For-Chicago/code-for-chicago-gatsby pull request #9
Opened 2022-11-16 22:43 UTC by demirsergen

- I found the icons that were used in this component from the current codeforchicago website (jekyll project). Followed the same folder structure -> created folder called join-us inside of images.
- I didn't think this wouldn't be a reusable component so I copied the content exactly.

2022-11-20 00:45 UTC, daleinen7 requested changes
A few minor changes, and then there's another PR's code on this one.

2022-11-20 00:45 UTC, daleinen7 commented on src/components/Card.jsx
> +import { Link } from 'gatsby'
Looks like this is code from the other PR. There's a couple things we can do to fix this.
1. We can revert this back to what it was before. You should be able to just copy and paste from the current code base. 
2. We can make sure to merge your other PR first then see what merge conflicts happen or see if this just resolves itself. 
Either way let's make sure these changes aren't on this PR just for consistency's sake.

2022-11-20 00:45 UTC, daleinen7 commented on src/components/Checklist.jsx
> +      <h1 class="joinHeader">Ready To Join?</h1>
Let's make this an `h3`.

2022-11-20 00:45 UTC, daleinen7 commented on src/components/Checklist.jsx
> +          <a href="https://codeforchicago.org/projects" target="_blank">
Let's make this a Gatsby `Link`.

2022-11-25 18:21 UTC, daleinen7 requested changes
One minor change and this will be ready to go.

2022-11-25 18:21 UTC, daleinen7 commented on src/components/Checklist.jsx
> +          <Link to="https://codeforchicago.org/projects" target="_blank">
Since this will be an internal link we can just make the "to" prop to just be `/projects`.

2022-12-04 06:15 UTC, daleinen7 requested changes
This looks good other than the Card component being a part of the PR.

2022-12-04 06:15 UTC, daleinen7 commented on src/components/Card.jsx
> +import React from 'react'
Still looks like the card component is on this PR. Let's figure out a way to remove this file from the PR. Let me know if you need help with this.

2022-12-04 06:24 UTC, demirsergen reviewed
I just deleted the Card.jsx file from the changed files section. Hope this will fix it!

2022-12-04 15:05 UTC, daleinen7 commented
> I just deleted the Card.jsx file from the changed files section. Hope this will fix it!

Looks like that brings up a conflict with the existing card component. Maybe merge with main then see if that resolves the conflict.

2022-12-04 16:13 UTC, closed without merging